# Generated by Django 3.2.5 on 2021-08-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='time of transaction'),
        ),
    ]
